#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
h=0
while ((h<13))
do
    echo Hour: $h
    m=1
    while ((m<60))
    do 
        echo $m
        ((m++))
    done
    ((h++))
done